### ISSUE TITLE
Question about random sampling.

### ISSUE THREAD

**Issue by SongRb** [codertimo/BERT-pytorch#13]
https://github.com/codertimo/BERT-pytorch/blob/7efd2b5a631f18ebc83cd16886b8c6ee77a40750/bert_pytorch/dataset/dataset.py#L50-L64

Well, seems `random.random()` always returns a positive number, so `prob >= prob * 0.9` will always be true?

**Comment by codertimo** [comment]
Haha your right it seems else is more efficient. thank you for your comment 👀

**Comment by codertimo** [comment]
@SongRb It would be great if you fix and pull request to me. then you could be contributor too! please let me know your thought :)

**Comment by artemisart** [comment]
I also think these conditions are still wrong, I'm sending a PR
