### ISSUE TITLE
Erroneous code

### ISSUE THREAD

**Issue by winitzki** [codertimo/BERT-pytorch#21]
https://github.com/codertimo/BERT-pytorch/blob/7efd2b5a631f18ebc83cd16886b8c6ee77a40750/bert_pytorch/dataset/dataset.py#L53-L62

This code is incorrect - it will always go into the last `if` clause. For instance, `prob < prob * 0.8` is never true.

**Comment by codertimo** [comment]
fixed by #22 duplicated with #13
