### ISSUE TITLE
Example of Input Data

### ISSUE THREAD

**Issue by nateraw** [codertimo/BERT-pytorch#28]
Could you give a concrete example of the input data? You gave an example of the corpus data, but not the dataset.small file found in this line:

`bert -c data/dataset.small -v data/vocab.small -o output/bert.model`

If you could show perhaps a couple of examples, that would be very helpful! I am new to pytorch, so the dataloader function is a little confusing.

**Comment by nateraw** [comment]
Why might this be happening then? I ran these lines...

```
bert-vocab -c data/dummy_data.small -o data/vocab.small

bert -c data/dummy_data.small -v data/vocab.small -o output/bert.model
```

<img width="1091" alt="screen shot 2018-10-23 at 1 33 54 am" src="https://user-images.githubusercontent.com/32437151/47343649-d9dc4d00-d663-11e8-9132-e8b0b8d76470.png">

**Comment by nateraw** [comment]
Dummy data looks like this:
<img width="397" alt="screen shot 2018-10-23 at 1 37 35 am" src="https://user-images.githubusercontent.com/32437151/47343861-45261f00-d664-11e8-8c67-fee373cf8a3c.png">

**Comment by codertimo** [comment]
@nateraw Can you update the bert-pytorch version to 0.0.1a4?
```
pip install -U bert-pytorch
```

**Comment by nateraw** [comment]
Interestingly, a different error:

<img width="1067" alt="screen shot 2018-10-23 at 1 49 48 am" src="https://user-images.githubusercontent.com/32437151/47344548-fc6f6580-d665-11e8-9e29-890384635fa2.png">

**Comment by codertimo** [comment]
@nateraw I got what was wrong with both your example corpus and mine.
We should not make a blank line in end of the line! If you check the line 18 at your corpus, 
`\n` is declared on last line, which means that python recognize there is one more extra line.
Please remove the `\n` of end of character at the end of line. that would be help to fix it

**Comment by nateraw** [comment]
Wow so dumb! My fault, I will report back if that change works or not.

**Comment by nateraw** [comment]
Issue was with the tabs as well. Replaced with literal tabs, and it worked. Closing the issue, thank you!
