### ISSUE TITLE
Single Sentence Input support

### ISSUE THREAD

**Issue by nateraw** [codertimo/BERT-pytorch#31]
In the paper, they note that they optionally use single sentence input for some classification tasks. I'll try to take a look at doing it myself, as it looks like it is not currently supported.

**Comment by codertimo** [comment]
@nateraw Well currently, BERT-pytorch only support 2sentences input.
Cause this implementation is only for training BERT, not for transfer learning :)

**Comment by codertimo** [comment]
But you can give a single sentence, if you change little bit of code 👍
