### ISSUE TITLE
shape match for mul？

### ISSUE THREAD

**Issue by guotong1988** [codertimo/BERT-pytorch#37]
https://github.com/codertimo/BERT-pytorch/blob/alpha0.0.1a5/bert_pytorch/model/embedding/position.py#L18

What are the shapes of `position` and `div_term`?

**Comment by nateraw** [comment]
It's fairly easy to step through the code to find the shape. d_model is the embedding size and max_len is the maximum length of a sequence. Hope this helps

![image](https://user-images.githubusercontent.com/32437151/47595685-c02a5680-d93e-11e8-9ddd-7df1e3675c56.png)
